= Developing
:link-repository: https://github.com/d4l-data4life/d4l-crypto-ios
:doctype: article
:toc: macro
:toclevels: 2
:toc-title:
:icons: font
:imagesdir: assets/images
ifdef::env-github[]
:warning-caption: :warning:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
endif::[]

Guide for our development process, project setup and how to write code.

[discrete]
==== Table Of Contents

toc::[]

== Prerequisites

* XCode 12.5
* iOS 13.0
* Swift 5.4+
* Bundler

== Installation

=== Install Gems using bundler

[source, bash]
----
bundle install
----

*Note*: Check the link:https://bundler.io/[official page] for info on how to install Bundler.

== Building

Just open XCode, let the packages resolve and build the Data4LifeCrypto Scheme.

=== Generate documentation

Documentation is generated using Asciidoctor, all of the resoures can be found in link:asciidoc/[asciidoc], and generated HTML documentation can be found in [docs](docs/).

[source, bash]
----
bundle exec fastlane generate_docs version:1.0.0
----

== Development Process

=== Features

Every change has to branch of from `main` and use this branch naming convention:

* `feature/{type_of_change}-{short_description}` or with ticket id `feature/{ticket_id}/{type_of_change}-{short_description}`

`main` must be always in releasable state.

==== Type Of Change

- *add* for new features or functionality
- *change* for changes in existing features or functionality
- *remove* | for removed features or functionality
- *fix* for any bug fixes
- *bump* for dependency updates
- *security* in case of vulnerabilities

Examples:

- `feature/SDK-456/add-awesome-hashing-algorithm`
- `feature/add-awesome-hashing-algorithm`
- `feature/remove-not-so-awesome-algorithm`
- `feature/fix-algorithm-corner-case`
- `feature/bump-lib-to-1.3.0`

== Release

A release branches of from `main` branch with following pattern:

* `release/{major}.{minor}(.{patch})/prepare-{major}.{minor}.{patch}` while patch is optional

Add following changes:

* Update CHANGELOG.adoc by creating a new Unreleased section and change current unreleased to release version
* Update README.adoc `crypto-version` to release version
* Update the latest release badge link:assets/images/badges.adoc[HowTo]

=== Manual steps

Updating link:CHANGELOG.md[CHANGELOG] is the only required manual step, release script expects to find matching version in the CHANGELOG.adoc as the one that used while calling `release_framework` Fastlane action. It takes all of the chnages and uploads them to the GitHub release page.

*Note*: Release script will fail if there is no new version defined in the changelog

=== Running the script
Folowing command will release new version of framework while handling couple of things:

* Set new project version
* Set new framework version
* Set new version in the README.adoc
* Generate new documentation
* Do sanity checks (proper branch, proper version number in changelog etc.)
* Commit changes and create version tag
* Push new commit and tag to GitHub
* Create GitHub release page with all of the information for [CHANGELOG.adoc](CHANGELOG.adoc)
* Upload prebuilt framework to the release page

[source, bash]
----
bundle exec fastlane release_framework version:"1.0.0" api_token:"super-secret-GitHub-API-token"
----