= Data4Life Crypto iOS SDK
:library_version: 1.6.0
:doctype: article
:!showtitle:
:toc: macro
:toclevels: 2
:toc-title:
:icons: font
:imagesdir: assets/images
:link-repository: https://github.com/d4l-data4life/d4l-crypto-ios
ifdef::env-github[]
:warning-caption: :warning:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
endif::[]

++++
<div align="center">
    <p><!-- PROJECT LOGO -->
        <a><img src="assets/images/d4l-logo.svg" width="150"/></a>
    </p>
    <p><!-- PROJECT TITLE -->
        <h3>Data4Life Crypto iOS</h3>
    </p>
    <p><!-- PROJECT DESCRIPTION -->
        Swift framework for handling all of the crypto operation for the Data4Life iOS frameworks.
    </p>
    <p><!-- PROJECT DOCUMENTATION -->
        <a href="README.adoc"><strong>Explore the docs »</strong></a>
    </p>
    <p><!-- PROJECT ISSUES/FEATURES -->
        <a href="https://github.com/d4l-data4life/d4l-crypto-ios/issues">Report Bug</a>
        ·
        <a href="https://github.com/d4l-data4life/d4l-crypto-ios/issues">Request Feature</a>
    </p>
    <p><!-- PROJECT BADGES see badges.adoc how to change them -->
        <a href="https://github.com/d4l-data4life/d4l-crypto-ios/releases">
            <img src="assets/images/badge-release-latest.svg" alt="Latest version"/>
        </a>
        <a href="https://github.com/d4l-data4life/d4l-crypto-ios/actions">
            <img src="https://github.com/d4l-data4life/d4l-crypto-ios/actions/workflows/pr-test.yml/badge.svg" alt="Build Status"/>
        </a>
        <a>
            <img src="assets/images/badge-platform-support.svg" alt="Platform"/>
        </a>
        <a href="LICENSE">
            <img src="assets/images/badge-license.svg" alt="License"/>
        </a>
    </p>
</div>
++++

[discrete]
=== Table Of Contents
toc::[]

== About The Project

Swift framework for handling all of the crypto operation for the Data4Life iOS frameworks.

== Installation

=== Swift Package Manager

To install with Swift package manager, select your project’s Swift Packages tab, and add our repository url, either as ssh or https url:

[source, terminal]
----
https://github.com/d4l-data4life/d4l-crypto-ios.git
----

OR

[source, terminal]
----
git@github.com:d4l-data4life/d4l-crypto-ios.git
----

In the next step, select the latest version, and then import the `Data4LifeCrypto` framework in your target.

== Features 

=== Supported symmetric algorithms
`Data4LifeCrypto` supports two modes of symmetric crypto operations:
* `AES-SHA256-CBC-PKCS7`
* `AES-SHA256-GCM-NOPADDING`

*Note*: Provided by Apple Cryptokit frameworks

=== Supported asymmetric algorithms
`Data4LifeCrypto` supports one mode of asymmetric crypto operations:
* `RSA-OAEP-SHA256`

*Note*: Provided by Apple Security framework

=== Storing and working with crypto keys
`KeyPair` is managed by Apple and has to be loaded using `Security` framework APIs that expect `tag`.
`Key` has to be stored manually in prefered storage of choice.

It's possible to generate `KeyPair` as it's stored on device, and use that to encrypt `Key`, that way it's possible to store data keys and encrypted sensitive information on the API.

Store keys and data:
* Generate `Key` for encrypting data (`KeyType.data`)
* Create key exchange format from the key type
* Encrypt sensitive data using generated `Key`
* Generate `KeyPair` for encrypting data key
* Convert data key from `Key` type to `Data` type (`Key` conforms to `Codable`)
* Encrypt key data using `KeyPair`
* Store ciphertext, iv and encrypted data key in some storage

Read keys and data:
* Load already created `KeyPair` from the device
* Load ciphertext, iv and encrypted data key from storage
* Decrypt data key using keypair
* Decrypt sensitive data using decrypted data key, ciphertext and iv

=== Key (symmetric)
Symmetric key used for encrypt/decrypt operations.

[source, swift]
----
struct Key: Codable {
    let value: SymmetricKey
    var algorithm: AlgorithmType
    let keySize: KeySize
    let type: KeyType
}
----

Create new key

[source, swift]
----
func generate(keySize: KeySize, algorithm: AlgorithmType, type: KeyType) throws -> Key
----

Create key from data. It will throw an error if the size of the data does not correspond to the key type.

[source, swift]
----
init(data: Data, type: KeyType) throws

// Exg.
let keyType: KeyType = .data
let key = Key(data: data, type: keyType)
----

Loading already existing key

[source, swift]
----
let keyData = Data(...) // load from some storage
let key = try JSONDecoder().decode(Key.self, from: keyData)
----

Exporting key for storage

[source, swift]
----
let key = Key.generate(...)
let keyData = try JSONEncoder().encode(key)
----

Example of creating a key and ecrypting data

[source, swift]
----
let keyType: KeyType = .data
let keyExchangeFormat = try KeyExhangeFactory.create(type: keyType)
let key = try Key.generate(keySize: keyExchangeFormat.size, algorithm: keyExchangeFormat.algorithm, type: type)
let iv = Data(bytes: [...]) // generate random IV

let plaintext: Data = Data(bytes: [0x00, 0x01, 0x02])
let ciphertext: Data = Data4LifeCryptor.symEncrypt(key: key, data: plaintext, iv: iv)
// Store ciphertext, iv and key in a safe way
----

Decrypt the data

[source, swift]
----
let key: Key =  ... // fetch key from storage
let iv: Data = ... // fetch iv from storage
let ciphertext: Data =  ... // fetch ciphertext from storage
let plaintext: Data = try Data4LifeCryptor.symDecrypt(key: key, data: ciphertext, iv: iv)
----

=== KeyPair (asymmetric)

[source, swift]
----
struct KeyPair: KeyPairType {
    let privateKey: AsymmetricKey
    let publicKey: AsymmetricKey
    let keySize: KeySize
    let algorithm: AlgorithmType
}
----

Helper methods for working with keypairs (wrapper around `Security` framework)

[source, swift]
----
func generate(tag: String, keySize: Int, algorithm: AlgorithmType) throws -> KeyPair
func load(tag: String, algorithm: AlgorithmType) throws -> KeyPair
func destroy(tag: String) throws
----

Exporting public key can be done in one of two formats `PKCS#1` or `SPKI`

[source, swift]
----
let keypair = try KeyPair.generate(...)

let pkcs1PubKey: String = keypair.publicKey.asBase64EncodedString()
let spkiPubKey: String = keypair.publicKey.asSPKIBase64EncodedString()
let pubKeyData: Data = JSONEncoder().encode(keypair) // will export `SPKI` encoded public key and ignore private key
----

Example of creating keypair and ecrypting data

[source, swift]
----
let tag: String = "com.example.keypair"
let keyType: KeyType = .appPrivate
let keyExchangeFormat = try KeyExhangeFactory.create(type: type)
let keypair = try KeyPair.generate(tag: tag, keySize: keyExchangeFormat.size, algorithm: keyExchangeFormat.algorithm)

let plaintext: Data = Data(bytes: [0x00, 0x01, 0x02])
let ciphertext: Data = try Data4LifeCryptor.asymEncrypt(key: keypair, data: plaintext)
----

Decrypt the data

[source, swift]
----
let tag: String = "com.example.keypair"
let keyType: KeyType = .appPrivate
let keyExchangeFormat = KeyExhangeFactory.create(type: type)
let keypair = try KeyPair.load(tag: tag, algorithm: keyExchangeFormat.algorithm)

let ciphertext: Data = ... // fetch ciphertext from storage
let plaintext: Data = try Data4LifeCryptor.asymDecrypt(key: keypair, data: ciphertext)
----

== Changelog

See link:CHANGELOG.adoc[changelog]

== Versioning

We use http://semver.org/[Semantic Versioning] as a guideline for our versioning.

Releases use this format: `{major}.{minor}.{patch}`

* Breaking changes bump `{major}` and reset `{minor}` & `{patch}`
* Backward compatible changes bump `{minor}` and reset `{patch}`
* Bug fixes bump `{patch}`

== Contributing

You want to help or share a proposal? You have a specific problem? Read the following:

* link:CODE-OF-CONDUCT.adoc[Code of conduct] for details on our code of conduct.
* link:CONTRIBUTING.adoc[Contributing] for details about how to report bugs and propose features.
* link:DEVELOPING.adoc[Developing] for details about our development process and how to build and test the project.

== Copyright and License

Copyright (c) 2021 D4L data4life gGmbH / All rights reserved. Please refer to our link:LICENSE[License] for further details.
