= PROJECT_TITLE
:link-repository: PROJECT_GITHUB_LINK
:project_version: PROJECT_VERSION
:doctype: article
:!showtitle:
:toc: macro
:toclevels: 2
:toc-title:
:icons: font
:imagesdir: assets/images
ifdef::env-github[]
:warning-caption: :warning:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
endif::[]

++++
<div align="center">
    <p> <!-- PROJECT LOGO -->
        <a href="PROJECT_GITHUB_LINK">
            <img src="assets/images/d4l-logo.svg" width="150"/>
        </a>
    </p>
    <p><!-- PROJECT TITLE -->
        <h3>PROJECT_TITLE</h3>
    </p>
    <p><!-- PROJECT DESCRIPTION -->
        PROJECT_DESCRIPTION
    </p>
    <p><!-- PROJECT DOCUMENTATION -->
        <a href="PROJECT_DOCUMENTATION_LINK"><strong>Explore the docs »</strong></a>
    </p>
    <p><!-- PROJECT ISSUES/FEATURES -->
        <a href="PROJECT_GITHUB_LINK/issues">Report Bug</a>
        ·
        <a href="PROJECT_GITHUB_LINK/issues">Request Feature</a>
    </p>
    <p><!-- PROJECT BADGES see badges.adoc how to change them-->
        <a href="PROJECT_GITHUB_LINK/releases">
            <img src="assets/images/badge-release-latest.svg" alt="Latest release"/>
        </a>
        <a>
            <img src="assets/images/badge-platform-support.svg" alt="Platform"/>
        </a>
        <a href="LICENSE">
            <img src="assets/images/badge-license.svg" alt="License"/>
        </a>
    </p>
</div>
++++

[discrete]
=== Table Of Contents

toc::[]

== About the Project

This is a blank template to get started. First replace following placeholders:

* PROJECT_TITLE
* PROJECT_DESCRIPTION
* PROJECT_GITHUB_LINK eg https://github.com/d4l-data4life/hc-gradle-scrips
* PROJECT_DOCUMENTATION_LINK

Assets could be placed under `assets/` folder and images should be placed in `assets/images/`.

And have a look link:https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/[Asciidoc Syntax Quick Reference] and link:https://asciidoctor.org/docs/asciidoc-writers-guide/[Asciidoc Writers Guide]

If you like to use badges, have a look at link:assets/images/badges.adoc[badges how to].

=== Features

// this section is optional

* List of features

=== Build With

// this section is optional

* link
* link
* link

== Getting Started

Instructions how to get software up and running.

=== Prerequisites

List things you need to use the software and how to install them.

* npm
* Gradle

=== Installation

A step by step series of examples that tell you how to get it running.

[source, lanugage]
----
Give the example
----

And repeat

[source, lanugage]
----
until finished
----

End with an example of getting some data out of the system or using a little demo

== Usage

Use this space to show useful examples of how a project can be used. Additional screenshots, code examples and demos work well in this space. You may also link to more resources.

For more examples, please refer to the link:PROJECT_DOCUMENTATION_LINK[Documentation]

== Roadmap

This project is work in progress. We are working on adding more functionality, guidelines, documentation and other improvements.

Next planed features:

* feature description

See the open link:{link-repository}/issues[issues] for a list of proposed features and known issues.

== Changelog

See link:CHANGELOG.adoc[changelog]

== Versioning

We use http://semver.org/[Semantic Versioning] as a guideline for our versioning.

Releases use this format: `{major}.{minor}.{patch}`

* Breaking changes bump `{major}` and reset `{minor}` & `{patch}`
* Backward compatible changes bump `{minor}` and reset `{patch}`
* Bug fixes bump `{patch}`

== Contributing

You want to help or share a proposal? You have a specific problem? Read the following:

* link:CODE-OF-CONDUCT.adoc[Code of conduct] for details on our code of conduct.
* link:CONTRIBUTING.adoc[Contributing] for details about how to report bugs and propose features.
* link:DEVELOPING.adoc[Developing] for details about our development process and how to build and test the project.

== Copyright and License

Copyright (c) 2021 D4L data4life gGmbH / All rights reserved.

Please refer to our link:LICENSE[License] for more information.

OR

Distributed under the MIT License. See link:LICENSE[License] for more information.

== FAQ

// this section is optional

Why this approach?:: Because ...

Could this be done better?:: Certainly ...

== Acknowledgements

// this section is optional

* Hat tip to anyone whose code was used
* Inspiration
* etc
